apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pong
  name: pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - image: ghcr.io/s1ntaxe770r/pong:f68dcb69afdc70c852f5f44e55e43e7b5dbc1b3b
        name: pong
